port: 7777
host: localhost
Player:
  respawns: 3
  health: 100
  radius: 1
  angle: 0
  bullets: 8
  speed: 5
  key: 0
  maxBullets: 50
  bulletsShot: 0
  playersKilled: 0
  score: 0
Weapons:
  knife:
    damage: 3
    minBullets: 0
    cooldownTimer: 50
  pistol:
    damage: 80
    minBullets: 1
    cooldownTimer: 50
  machine gun:
    damage: 30
    minBullets: 5
    cooldownTimer: 30
  chain gun:
    damage: 40
    minBullets: 1
    cooldownTimer: 10
  rocket launcher:
    damage: 50
    minBullets: 5
    cooldownTimer: 100