port: 7777
host: localhost
Player:
  lifes: 1
  health: 100
  radius: 1
  angle: 0
  bullets: 8
  speed: 5
  key: 0
  maxBullets: 50
  bulletsShot: 0
  playersKilled: 0
  score: 0
Weapons:
  knife:
    damage: 300
    minBullets: 0
    cooldownTimer: 70
  pistol:
    damage: 20
    minBullets: 1
    cooldownTimer: 75
  machine gun:
    damage: 30
    minBullets: 5
    cooldownTimer: 100
  chain gun:
    damage: 40
    minBullets: 1
    cooldownTimer: 150
  rocket launcher:
    damage: 50
    minBullets: 5
    cooldownTimer: 20