Player:
  lifes: 3
  health: 100
  radius: 1
  angle: 0
  bullets: 15
  speed: 5
  key: 0
  maxBullets: 50
  bulletsShot: 0
  playersKilled: 0
  score: 0
Weapons:
  knife:
    damage: 3
    minBullets: 0
    cooldownTimer: 70
  pistol:
    damage: 20
    minBullets: 1
    cooldownTimer: 75
  machine gun:
    damage: 30
    minBullets: 5
    cooldownTimer: 20
  chain gun:
    damage: 40
    minBullets: 1
    cooldownTimer: 20
  rocket launcher:
    damage: 50
    minBullets: 5
    cooldownTimer: 20
