Player:
  lifes: 3
  health: 20
  radius: 2
  angle: 0
  bullets: 8
  key: 0
  maxBullets: 50
  bulletsShot: 0
  playersKilled: 0
  score: 0
Weapons:
  knife:
    damage: 1
    minBullets: 0
    cooldownTimer: 0
  pistol:
    damage: 1
    minBullets: 1
    cooldownTimer: 0
  machine gun:
    damage: 5
    minBullets: 5
    cooldownTimer: 9
  chain gun:
    damage: 6
    minBullets: 1
    cooldownTimer: 3
  rocket launcher:
    damage: 1
    minBullets: 5
    cooldownTimer: 0

