Player:
  lifes: 3
  health: 100
  radius: 2
  angle: 0
  bullets: 8
  maxBullets: 50
  bulletsShot: 0
  playersKilled: 0
Weapons:
  knife:
    damage: 1
    minBullets: 0
    speed: 0
  pistol:
    damage: 1
    minBullets: 1
    speed: 0
  machine gun:
    damage: 5
    minBullets: 5
    speed: 0.3
  chain gun:
    damage: 6
    minBullets: 1
    speed: 0.1
  rocket launcher:
    damage: 1
    minBullets: 5
    speed: 0.0

