Player:
  lifes: 3
  health: 100
  radius: 2
  angle: 0
  bullets: 8
Weapons:
  Knife:
    damage: 1
    minBullets: 0
    speed: 0
  Gun:
    damage: 1
    minBullets: 1
    speed: 0
  MachineGun:
    damage: 5
    minBullets: 5
    speed: 0.3
  ChainCanon:
    damage: 6
    minBullets: 1
    speed: 0.1
  Rocket:
    damage: 1
    minBullets: 5
    speed: 0.0

